# Generated by Django 2.0.1 on 2018-01-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateField(verbose_name='creation date')),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aggregate', models.CharField(max_length=200)),
                ('added', models.DateField(verbose_name='added date')),
                ('date', models.DateField(verbose_name='Date of item origin, in ex. book release date, wine production year etc.')),
                ('desc', models.CharField(max_length=2000)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collectionsapp.Collection')),
            ],
        ),
    ]
