# Generated by Django 2.0.1 on 2018-01-31 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 19, 21, 28, 849458, tzinfo=utc), verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='added',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 19, 21, 28, 869469, tzinfo=utc), verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='aggregate',
            field=models.CharField(max_length=200, verbose_name='Agregat (np. autor, zespół)'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collectionsapp.Collection', verbose_name='Kolekcja'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='date',
            field=models.DateField(verbose_name='Data produkcji przedmiotu, np. data wydania książki, rocznik wina itd.'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='desc',
            field=models.CharField(max_length=2000, verbose_name='Opis przedmiotu'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
    ]
