# Generated by Django 2.0.2 on 2018-02-03 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0002_auto_20180131_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 16, 50, 33, 883498, tzinfo=utc), verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='added',
            field=models.DateField(default=datetime.datetime(2018, 2, 3, 16, 50, 33, 905001, tzinfo=utc), verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionsapp.Collection', verbose_name='Kolekcja'),
        ),
    ]
