# Generated by Django 2.0.1 on 2018-02-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectionsapp', '0003_auto_20180203_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='collectionvalue',
            name='added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
    ]
