# Generated by Django 2.0.1 on 2018-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0004_auto_20180203_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_logo',
            field=models.FileField(default=1, upload_to='', verbose_name='Logo'),
        ),
    ]
