# Generated by Django 2.0.1 on 2018-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0005_collection_collection_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_logo',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
