# Generated by Django 2.0.1 on 2018-02-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0006_auto_20180205_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
