# Generated by Django 2.0.1 on 2018-02-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0008_auto_20180205_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
