# Generated by Django 2.0.1 on 2018-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionsapp', '0009_auto_20180205_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionvalue',
            name='collectionValue_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
